### ISSUE TITLE
Version too clever. breaks.

### ISSUE THREAD

**Issue by do3cc** [bwesterb/py-tarjan#4]
We are installing tarjan via buildout, probably the same problem exists with pip.
In proper buildout configurations you pin every package to a specific version. 
We pinned tarjan to 0.1.2. Buildout finds tarjan on pypi as a source release, downloads it and builds an egg out of it.
When building the egg, the version of the egg is infered by what is written in setup.py. 
That ```get_git_version()``` For some reason returns a version 1.0.1. My buildout realizes that it got the wrong egg and bails out. This happens with 0.1.2 and 0.2.1.

If the version number were just a string, this problem would not exist. I can provide a PR for it and would be very glad for a new egg with a static version.
I'd like to use this opportunity to mention a package I did not write but use a lot: https://pypi.python.org/pypi/zest.releaser Which is an alternative way to avoid updating a version number by hand.

**Comment by bwesterb** [comment]
Thank you for reporting the issue.  If you could write a pull-request, that would be great!  I could also try it myself, but then it would require some back-and-forth  to fix the problem for you.

**Comment by bwesterb** [comment]
I just released 0.2.2.  Did this solve your problem?

**Comment by bwesterb** [comment]
Please check whether 0.2.3 is fine as well.

**Comment by do3cc** [comment]
works good now, thanks!
