### ISSUE TITLE
Unable to install 0.2.2 with pip

### ISSUE THREAD

**Issue by leolchat** [bwesterb/py-tarjan#6]
The tarball at https://pypi.python.org/pypi/tarjan/0.2.2
doesn't contain CHANGES.rst
which crashes the installation with pip.

**Comment by maethu** [comment]
I confirm our CI also complains about the same.

**Comment by maethu** [comment]
You need to configure the MANIFEST.in properly:

```
inlcude src
global-exclude *.pyc
...

**Comment by avoinea** [comment]
+!

**Comment by bwesterb** [comment]
I'm traveling to work. I'll fix this when I arrive.  Sorry for the inconvenience.

**Comment by bwesterb** [comment]
Should be fixed in `0.2.3`.

**Comment by maethu** [comment]
@bwesterb Thanks for the fast bugfix release! I works fine again :smile:

**Comment by bwesterb** [comment]
No problem!  Happy to help out.
