### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by pombredanne** [bwesterb/py-tarjan#7]
@bwesterb Thank you for this great lib. Note that it is used in https://github.com/debrouwere/python-whatwhen by @debrouwere that is ISC-licensed. I am also considering it for use in the Apache-licensed https://github.com/nexB/scancode-toolkit .
The AGPL license means it is not easy to use your code as a library unless the using code is also AGPL or AGPL compatible and treated as AGPL-licensed practically at runtime. 
Would you consider another license such the LGPL instead?
Please ignore if you feel strongly about this!
Thank you.

**Comment by bwesterb** [comment]
I relicensed to LGPLv3.

**Comment by pombredanne** [comment]
@bwesterb You are a prince and a very quick prince at that! Thank you!

**Comment by pombredanne** [comment]
@do3cc just to be hyper clear: are you OK with the new license since your contributed to this repo too?

**Comment by do3cc** [comment]
Yes, i am OK with the new license
