### ISSUE TITLE
Republish package to PyPI with new license

### ISSUE THREAD

**Issue by thejcannon** [bwesterb/py-tarjan#9]
I see the license changed 5 years ago: https://github.com/bwesterb/py-tarjan/blob/master/LICENSE however the latest release on PyPI is still licensed "GNU AFFERO GENERAL PUBLIC LICENSE" and the trove classifier is `          'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',`

Thanks!

**Comment by bwesterb** [comment]
Should be solved now.

**Comment by thejcannon** [comment]
That was quick! Thanks!
